### ISSUE TITLE
Fatal error: Must have callback

### ISSUE THREAD

**Issue by embrown30** [iandotkelly/grunt-license-finder#5]
I'm getting this error when trying to retrieve licenses now
![image](https://cloud.githubusercontent.com/assets/5648812/14851327/29e86efc-0c4d-11e6-84b4-d8baa375c3d0.png)

I tried from the node_modules/grunt-license-finder directory as well just to be sure it wasn't in our grunt file and got the same error when I run grunt test

I just updated grunt this morning to check and see if the version was the issue:
grunt-cli v1.2.0
grunt v0.4.5

But it still didn't work.

**Comment by iandotkelly** [comment]
Closed with https://github.com/iandotkelly/grunt-license-finder/releases/tag/1.3.0
